package com.switchfully.eurder.utils;

public enum Feature {
	VIEW_ALL_CUSTOMERS,
	VIEW_CUSTOMER_BY_ID,
	CREATE_NEW_ORDER,
	VIEW_MY_ORDERS,
	REORDER_ORDER,
	CREATE_NEW_ITEM,
    UPDATE_ITEM,
    GET_ITEMS,
	GET_ITEMS_ON_URGENCY,
	GET_SHIPPING_LIST
}
